<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */ ?>
<?php
$_order = $block->getOrder();
$blockInfoObj= $block->getLayout()->createBlock('Magenest\OrderAttribute\Block\Adminhtml\Order\View\Tab\Info');
$_data = $blockInfoObj->getOrderAttribute();
$countryName = $blockInfoObj->getCountryNameByIp();
$blockOptionObj = $block->getLayout()->createBlock('Magenest\OrderAttribute\Block\Adminhtml\Attribute\Edit\Tab\Option');
?>

<div id="order-messages">
    <?php echo $block->getChildHtml('order_messages') ?>
</div>

<?php echo $block->getChildHtml('order_info') ?>

<!--        custom code for additional attribute-->
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?php echo __('Additional Attributes') ?></span>
        <div class="actions"></div>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <?php if ($_data): ?>
                        <?php foreach ($_data as $data):
                            if(($data->getCountryId()==null || $countryName == $blockInfoObj->getCountrynameByCode($data->getCountryId()) )
                                && $data->getIsVisibleOnBack()==1) {
                                $option = $blockOptionObj->getOptionArrayById($data->getAttributeId());
                                $valueAttribute = $blockInfoObj->getOrderAttributeValue($_order->getId(), $data->getAttributeId());
                                if ($valueAttribute != '') {
                                    if ($data->getFrontendInput() == 'multiselect' || $data->getFrontendInput() == 'select') {
                                        $values = unserialize($valueAttribute);
                                        $valueAttribute = '';

                                        foreach ($values as $val) {
                                            $valueAttribute .= $option[$val]['title'] . ',';
                                        }
                                        $valueAttribute = rtrim($valueAttribute, ',');
                                    }
                                    ?>
                                    <tr>
                                        <th><?php echo $data->getFrontendLabel(); ?></th>
                                        <td><strong><?php echo $valueAttribute ?></strong></td>
                                    </tr>
                                    <?php
                                } else {
                                    ?>
                                    <tr>
                                        <th><?php echo $data->getFrontendLabel(); ?></th>
                                        <td><strong><?php echo $data->getDefaultValue(); ?></strong></td>
                                    </tr>
                                    <?php
                                }
                            }
                            endforeach;?>
                    <?php else: ?>
                        <tr>
                            <th>&nbsp;</th>
                            <td><?php echo __('No attributes for this order'); ?></td>
                        </tr>
                    <?php endif;?>
                </table>
            </div>
        </div>
    </div>
</section>
<!--/custom code-->
<input type="hidden" name="order_id" value="<?php /* @escapeNotVerified */ echo $_order->getId() ?>"/>

<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Payment &amp; Shipping Method') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method<?php if ($_order->getIsVirtual()): ?> order-payment-method-virtual<?php endif; ?>">
            <?php /* Payment Method */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Payment Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-method-title"><?php echo $block->getPaymentHtml() ?></div>
                <div class="order-payment-currency"><?php /* @escapeNotVerified */ echo __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?></div>
                <div class="order-payment-additional">
                    <?php echo $block->getChildHtml('order_payment_additional'); ?>
                    <?php echo $block->getChildHtml('payment_additional_info'); ?>
                </div>
            </div>
        </div>
        <?php echo $block->getChildHtml('order_shipping_view') ?>
    </div>
</section>

<?php echo $block->getGiftOptionsHtml() ?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Items Ordered') ?></span>
    </div>
    <?php echo $block->getItemsHtml() ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Order Total') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Notes for this Order') ?></span>
            </div>
            <?php echo $block->getChildHtml('order_history') ?>
        </div>

        <div class="admin__page-section-item order-totals">
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Order Totals') ?></span>
            </div>
            <?php echo $block->getChildHtml('order_totals') ?>
        </div>
    </div>
</section>

<?php echo $block->getChildHtml('popup_window');?>

<script>
    require([
        "prototype",
        "Magento_Sales/order/giftoptions_tooltip"
    ], function(){

//<![CDATA[
        /**
         * Retrieve gift options tooltip content
         */
        function getGiftOptionsTooltipContent(itemId) {
            var contentLines = [];
            var headerLine = null;
            var contentLine = null;

            $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
                if (element.down(0)) {
                    headerLine = element.down(0).innerHTML;
                    contentLine = element.down(0).next().innerHTML;
                    if (contentLine.length > 30) {
                        contentLine = contentLine.slice(0,30) + '...';
                    }
                    contentLines.push(headerLine + ' ' + contentLine);
                }
            });
            return contentLines.join('<br/>');
        }
        giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
        window.getGiftOptionsTooltipContent = getGiftOptionsTooltipContent;
//]]>

    });
</script>
